### ISSUE TITLE
Decode string failed

### ISSUE THREAD

**Issue by kavat** [neoxic/lua-amf3#8]
Hi all,
I've a problem with this library, I don't know if I'm wrong but I try to explain my steps:
- I've a string that I give by modsecurity (binary string)
- When I pass this buffer (without any modification) to amf3_decode function the result is nil value
This is my code:

function main()
        local amf3 = require 'amf3'
        local amf3_decode = amf3.decode

        local stream = m.getvar("STREAM_INPUT_BODY")
        m.log(1, stream) -- log1
        m.log(1, amf3_decode(stream)) --log2

        return nil;
end

When I try to print the log1 I see an empty string but I think it's normal because the first chars is \x00.

Can you help me please?

Thanks

**Comment by neoxic** [comment]
If the first character of the string is \x00 (AMF3_NULL), then it is legitimately decoded as `nil`.
